### ISSUE TITLE
看好你，我也在你的基础上打算做一个仿照微信的定火车票的app方便交流下吗？

### ISSUE THREAD

**Issue by keylorsdu** [Akari10032/12306#1]
比如：你的UI是用什么工具画的？

**Comment by Akari10032** [comment]
原生控件吧，Material Design，一种设计规范，你可以看看这些：
[http://www.uisdc.com/comprehensive-material-design-note](url)
[https://www.materialpalette.com/](url)

**Comment by Akari10032** [comment]
最常用的比如padding:16dp, 正文14sp等等，按照规范来设计，搭配调色板选颜色，会得到比较好看的UI效果

**Comment by keylorsdu** [comment]
谢谢哈，学习了
